POST http://localhost:3001/api/User HTTP/1.1
content-type: application/json 


{  
  "email": "gjarju99@gmail",
  "password": "98765432",
  "firstname": "gee",
  "minit": "",
  "lastname": "jarju"
  
}



