GET http://localhost:3001/api/user/63520fbd3fd62deda06ba216


### Sale
GET http://localhost:3001/api/sale/6379aad7a3a4c83b53f09bf0
content-type: application/json


{
"userId": "6379aa35a3a4c83b53f09bed"
}

